### ISSUE TITLE
Создать компонент кнопки

### ISSUE THREAD

**Issue by vinokurov-and** [vinokurov-and/kguProject#11]
Создать компонент кнопки

Расположить его в ./src/components/Button/Button.js

Пример такой кнопки отображен на картинке:

<img width="1035" alt="image" src="https://github.com/vinokurov-and/kguProject/assets/48560509/811e7b0d-6bfc-4c74-acbf-8f6bc8e718d1">

----------------------------
Если задание непонятно или кажется сложным, у вас паника)) то ничего страшного. Попробуйте сделать что-то и опубликовать это на своей ветке под эту задачу. Попробуйте задать вопросы мне, что непонятно или уточните какие-то детали. Я здесь чтобы помогать вам.

**Comment by qwejid** [comment]
Вроде сделано если это то что надо было

**Comment by vinokurov-and** [comment]
@qwejid а где пулл-реквест?)

**Comment by vinokurov-and** [comment]
https://github.com/vinokurov-and/kguProject/wiki/%D0%9F%D0%BE%D1%88%D0%B0%D0%B3%D0%BE%D0%B2%D0%B0%D1%8F-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B8%D1%87%D0%BA%D0%B0-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F

Последний пункт
